Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
health=pd.read_csv('health.csv')[['Name', 'SSN', 'Marital status', 'Sex', 'DOB', 'Zip', 'Ethnicity', 'Problem' ]]
health[['Marital status', 'Sex', 'Zip', 'Ethnicity', 'Problem' ]]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m health[38;5;241m=[39m[43mpd[49m[38;5;241m.[39mread_csv([38;5;124m'[39m[38;5;124mhealth.csv[39m[38;5;124m'[39m)[[[38;5;124m'[39m[38;5;124mName[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSSN[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mMarital status[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSex[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDOB[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mZip[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEthnicity[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mProblem[39m[38;5;124m'[39m ]]
[1;32m      2[0m health[[[38;5;124m'[39m[38;5;124mMarital status[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSex[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mZip[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEthnicity[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mProblem[39m[38;5;124m'[39m ]]

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

